### ISSUE TITLE
протестить оффер тинька - ипотека

### ISSUE THREAD

**Issue by badrhari1777** [LDWizards/LDwizards#7]
создать страницу - витрину по ипотеке, запустить кампанию, проанализировать + или -

**Comment by Alexandr1777** [comment]
Привет, гео в рекламе показы по Тиньку для начала наверное давай сделаем?

**Comment by Alexandr1777** [comment]
Цена клика по ипотеке в среднем 0,4-0,6 центов

**Comment by badrhari1777** [comment]
для начала покажи сраницу, чтобы я оффера глянул. ГЕО примерно будет либо тинек, да, либо тинек + еще оффер с ислюкчением. Т.е. только что для двух подходит. Клик конечно вкурсе что большой.

**Comment by Alexandr1777** [comment]
http://одобрим-заявку.онлайн/ipoteka

**Comment by badrhari1777** [comment]
добавь к офферам ставрополь) посмотреть страницу

**Comment by Alexandr1777** [comment]
Ага добавил)

**Comment by badrhari1777** [comment]
срок в тиньке добавить надо

**Comment by Alexandr1777** [comment]
Ок
